#
server:
  port: 9018
  servlet:
    context-path: /chr-ftp
spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  application:
    name: chr-ftp

# sftp
sftp:
  host: 10.40.171.13
  port: 2233
  username: sftpuser
  password: b3mr~N_ptFDx
  session-timeout: 30000 # 会话超时
  channel-timeout: 5000 # 通道超时
